spring:
  application:
    name: SermonArchive
  datasource:
    url: jdbc:postgresql://localhost:5332/sermonmedia?currentSchema=public
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
        format_sql: false
    show-sql: false
jwt:
  secret: EueJZwlh7pEpVPHzDYjybR0xMwxtCxIRkFvGdqjZMro
  expiration: 360000

