spring:
  application:
    name: SermonArchive
  datasource:
    url: jdbc:postgresql://localhost:5332/sermonmedia?currentSchema=public
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: public
        format_sql: true
    show-sql: true
